# Generated by Django 4.2 on 2023-05-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_show_actors_show_director_show_theatre'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='premiere',
            field=models.BooleanField(default=False),
        ),
    ]
