# Generated by Django 4.2 on 2023-05-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_show_premiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='actors',
            field=models.ManyToManyField(null=True, to='api.actor'),
        ),
    ]
