# Generated by Django 4.2 on 2023-05-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_show_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, to='api.actor'),
        ),
    ]
