# Generated by Django 4.2 on 2023-05-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_show_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
