# Generated by Django 4.2 on 2023-05-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_show_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
