# Generated by Django 4.2 on 2023-06-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_show_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='actors',
        ),
        migrations.AddField(
            model_name='show',
            name='ticket_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
