# Generated by Django 4.2 on 2023-06-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_show_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='favourite',
        ),
    ]
